import unittest
from queue import LifoQueue
from unittest.mock import patch, Mock, call

class AsynchronousServiceTest(unittest.TestCase):
    def setUp(self):
        self.service = AsynchronousService(LifoQueue())
        self.task = Mock()

    @patch('task.call')
    def test_perfect_execution(self, mock_call):
        result = object()
        mock_call.return_value = result
        self.service.execute(self.task)

        self.task.on_post_call.assert_called_once_with(result)
        self.task.on_pre_call.assert_called_once()
        self.task.call.assert_called_once()
        self.task.on_post_call.assert_called_once_with(result)

    @patch('task.call')
    def test_call_exception(self, mock_call):
        exception = Exception()
        mock_call.side_effect = exception
        self.service.execute(self.task)

        self.task.on_error.assert_called_once_with(exception)
        self.task.on_pre_call.assert_called_once()
        self.task.call.assert_called_once()

    @patch('task.on_pre_call')
    def test_pre_call_exception(self, mock_on_pre_call):
        exception = Exception()
        mock_on_pre_call.side_effect = exception
        self.service.execute(self.task)

        self.task.on_error.assert_called_once_with(exception)
        self.task.on_pre_call.assert_called_once()
        self.task.on_error.assert_called_once_with(exception)


class AsynchronousService:
    def __init__(self, queue):
        self.queue = queue

    def execute(self, task):
        try:
            task.on_pre_call()
            result = task.call()
            task.on_post_call(result)
        except Exception as e:
            task.on_error(e)

if __name__ == '__main__':
    unittest.main()
